name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install node_modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Deploying the project
        run: yarn deploy
      - name: Setup finish
        run: echo "hurray!"
