name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install node_modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Deploying the project
        env:
          VERCEL_ORG_ID: YPC0yWbYAyb4fYsWHRM5rA7P
          VERCEL_PROJECT_ID: prj_UV8LLojQZLA0it3E1kDDSVwQoaUU
        run: yarn deploy
      - name: Setup finish
        run: echo "hurray!"
